[package]
name = "objpoke"
version = "0.1.0"
authors = ["tux3 <barrdetwix@gmail.com>"]
edition = "2018"

[dependencies]
goblin = "0.3"
eyre = "0.6.3"
scroll = "0.10"
structopt = "0.3"
regex = "1.3.9"
